# Generated by Django 3.1.4 on 2020-12-31 03:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myDBMSapp', '0003_auto_20201230_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myDBMSapp.register'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_messaged',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 31, 8, 12, 15, 326418)),
        ),
    ]
