# Generated by Django 3.1.4 on 2021-01-03 03:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myDBMSapp', '0004_auto_20201231_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='register',
            name='userMain',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_messaged',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 8, 13, 50, 511999)),
        ),
        migrations.AlterField(
            model_name='contact',
            name='purpose',
            field=models.CharField(choices=[('Suggession', 'Suggession'), ('Complaint', 'Complaint'), ('Appreciation', 'Appreciation'), ('Request', 'Request')], default='Suggession', max_length=20, verbose_name='purpose'),
        ),
        migrations.AlterField(
            model_name='register',
            name='designation',
            field=models.CharField(choices=[('User', 'Just a User'), ('Contributor', 'Contributor'), ('Editor', 'Editor')], default='User', max_length=20, verbose_name='designation'),
        ),
    ]
