# Generated by Django 3.1.4 on 2021-01-03 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDBMSapp', '0005_auto_20210103_0813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='userMain',
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_messaged',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 3, 9, 19, 46, 883150)),
        ),
    ]
