# Generated by Django 3.1.4 on 2021-01-04 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDBMSapp', '0009_auto_20210104_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_messaged',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 15, 13, 22, 584585)),
        ),
        migrations.AlterField(
            model_name='register',
            name='profile_pic',
            field=models.ImageField(blank=True, default='users/default-avatar.png', null=True, upload_to='users/'),
        ),
    ]
