# Generated by Django 3.1.4 on 2021-01-04 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDBMSapp', '0012_auto_20210104_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_messaged',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 4, 19, 11, 27, 55759)),
        ),
    ]
