# Generated by Django 3.1.4 on 2021-01-05 16:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myDBMSapp', '0018_auto_20210105_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionFileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contFileType', models.CharField(choices=[('PDF Notes', 'PDF Notes'), ('PDF Books', 'PDF Books'), ('Link', 'Link')], default='PDF Notes', max_length=20, verbose_name='contFileType')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseTitle', models.CharField(choices=[('ITC', 'ITC'), ('EMT', 'EMT'), ('Calculus-1', 'Calculus-1'), ('Writing-Wrokshop', 'Writing-Wrokshop'), ('Statistics', 'Statistics')], default='PDF Notes', max_length=20, verbose_name='COURSES')),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_messaged',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 21, 59, 29, 967417)),
        ),
        migrations.CreateModel(
            name='Contributions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100)),
                ('contribution_title', models.CharField(max_length=100)),
                ('contribFileType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myDBMSapp.contributionfiletype')),
                ('courseTitle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myDBMSapp.courses')),
                ('register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myDBMSapp.register')),
            ],
        ),
    ]
