# Generated by Django 3.1.4 on 2021-01-05 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDBMSapp', '0020_auto_20210105_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributions',
            name='contribution_file',
            field=models.FileField(blank=True, null=True, unique=True, upload_to='contributions/'),
        ),
        migrations.AddField(
            model_name='contributions',
            name='contribution_link',
            field=models.URLField(blank=True, max_length=128, null=True, unique=True, verbose_name='Content-Link'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_messaged',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 5, 22, 16, 54, 814218)),
        ),
    ]
