# Generated by Django 3.1.4 on 2021-01-06 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDBMSapp', '0021_auto_20210105_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_messaged',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 6, 13, 40, 32, 406912)),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='contribution_file',
            field=models.FileField(blank=True, null=True, upload_to='contributions/'),
        ),
    ]
