# Generated by Django 3.1.4 on 2021-01-12 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDBMSapp', '0023_auto_20210106_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_messaged',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 12, 47, 59, 612817)),
        ),
    ]
