# Generated by Django 3.1.4 on 2021-01-12 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myDBMSapp', '0024_auto_20210112_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='userMain',
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_messaged',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 13, 53, 24, 765118)),
        ),
    ]
