# Generated by Django 3.1.4 on 2021-01-12 09:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myDBMSapp', '0025_auto_20210112_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_messaged',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 14, 10, 55, 320992)),
        ),
        migrations.AlterField(
            model_name='contributions',
            name='register',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myDBMSapp.register'),
        ),
    ]
